baseURL = "https://gotpop.netlify.app/"
languageCode = "en-GB"
title = "Got"

[module]
[[module.imports]]
disable = false
path = "github.com/gotpop/gotscss"

[[module.imports.mounts]]
source = "styles"
target = "assets"

[[module.imports]]
path = "github.com/gohugoio/hugo-mod-heroicons"