baseURL = "https://gotpop.netlify.app/"
languageCode = "en-GB"
title = "Got"
logoIcon = "adjustments"

[params]
wrap = true
headerLogo = true
headerNav = true
logoIcon = "adjustments"

[module]

[[module.imports]]
disable = false
path = "github.com/gotpop/gotscss"

[[module.imports.mounts]]
source = "styles"
target = "assets"

[[module.imports]]
path = "github.com/gohugoio/hugo-mod-heroicons"