baseURL = "https://gotpop.netlify.app/"
languageCode = "en-GB"
title = "Got"
[params]
    wrap = true
[module]
    [[module.imports]]
        disable = false
        path = "github.com/gotpop/gotscss"
            [[module.imports.mounts]]
                source = "styles"
                target = "assets"
