backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
# publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Site Settings'
        file: 'data/settings.json'
        description: 'General Site Settings'
        fields:
          - { label: 'Global title', name: 'site_title', widget: 'string' }
          - { label: 'Display site title', name: 'display_site_title', widget: "boolean", default: true }
          - { label: 'Display site icon', name: 'display_site_icon', widget: "boolean", default: true }
          - label: "Menu Icon"
            name: "logoIcon"
            widget: "select"
            options: 'data/icons.json'
  - label: "Work"
    name: "work"
    folder: "work"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Menu Icon"
            name: "menu.mainmenu.params.menuIcon"
            widget: "select"
            options:
              - { label: "Academic cap", value: "academic-cap.svg" }
              - { label: "Adjustments", value: "adjustments.svg" }
              - { label: "Annotation", value: "annotation.svg" }
      - label: "Work Page"
        name: "work"
        file: "content/work/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
