backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
# publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Work"
    name: "work"
    folder: "work"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "posts"
    name: "posts"
    widget: "list"
    fields:
      - { label: "Source", name: "src", widget: "string" }
      - { label: "Alt Text", name: "alt", widget: "string" }
